name: Lint

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.13]
        toxenv: [isort, black, flake8]

    steps:
      - uses: actions/checkout@v4

      - name: pip cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ matrix.toxenv }}-pip-${{ hashFiles('**/setup.py') }}
          restore-keys: |
            ${{ matrix.toxenv }}-pip-

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade tox

      - name: Lint
        run: tox -e ${{ matrix.toxenv }}
